@startuml

box "Sequence Digram from QPS to PKB" #LightCyan
activate QPS

QPS -> PKBHandler: getStatementsList();

activate PKBHandler

PKBHandler -> StatementsStorage: getStatementsList();
activate StatementsStorage

StatementsStorage --> PKBHandler: return statementsList
deactivate StatementsStorage

PKBHandler --> QPS: return statementsList
deactivate PKBHandler

alt relRef Follows
  QPS -> PKBHandler: getFollows();
  activate PKBHandler
  PKBHandler -> FollowsStorage: getFollows();
  activate FollowsStorage
  FollowsStorage --> PKBHandler: return followsList
  deactivate FollowsStorage
  PKBHandler --> QPS: return followsList
  deactivate PKBHandler

else relRef Follows*
  QPS -> PKBHandler: getFollowsStar();
  activate PKBHandler
  PKBHandler -> FollowsStorage: getFollowsStar();
  activate FollowsStorage
  FollowsStorage --> PKBHandler: return followsStarList
  deactivate FollowsStorage
  PKBHandler --> QPS: return followsStarList
  deactivate PKBHandler

else relRef Parent
  QPS -> PKBHandler: getParent();
  activate PKBHandler
  PKBHandler -> ParentStorage: getParent();
  activate ParentStorage
  ParentStorage --> PKBHandler: return parentList
  PKBHandler --> QPS: return parentList
  deactivate ParentStorage

  deactivate PKBHandler
  end

QPS -> PKBHandler: getPattern(LHS, RHS);
activate PKBHandler
PKBHandler -> PatternStorage: getPattern(LHS, RHS);
activate PatternStorage
PatternStorage --> PKBHandler: return patternList
deactivate PatternStorage
PKBHandler --> QPS: return patternList
deactivate PKBHandler


deactivate QPS
end box

@enduml