name: CI for C++ linting
on: [ pull_request ]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
      - run: pip install cpplint
      - run: |
          cd Team16/Code16/src/spa
          cpplint --recursive --exclude=src/qps/constants.h --exclude=src/qps/query_parser/query_tokenizer/query_tokenizer.cpp --exclude=src/qps/query_parser/query_tokenizer/query_tokenizer.h --exclude=src/utils/string_utils.cpp --filter=-legal/copyright,-runtime/references --linelength=120 extensions=cpp,h .
